### ISSUE TITLE
Move cell keyboard shortcut disappeared

### ISSUE THREAD

**Issue by kotrfa** [jupyter/jupyter_notebook#21]
Hello,

I can't find keyboard shortcut for moving cell in Jupyter. I have long notebooks (like 100+ cells) and moving cells by mouse clicking on menu is unbearable...

Is there a reason for disabling this future? It used to be ctrl+k,j.

**Comment by jhamrick** [comment]
I believe the reason is that those keyboard shortcuts conflict with some browser shortcuts. If you want to re-enable them for yourself, you can edit your `custom.js`, as described in this issue: https://github.com/ipython/ipython/pull/7732

**Comment by kotrfa** [comment]
Ok, thank you for you answer.

**Comment by jkokorian** [comment]
Does that also work in jupyter notebook? The referenced post seems to apply to ipython notebook. I can't run the code that @Carreau suggested. When I try to run:

    IPython.keyboard_manager.command_shortcuts.add_shortcut('Shift-k','ipython.move-selected-cell-up')

I get an error:

    ImportError: No module named keyboard_manager

**Comment by jkokorian** [comment]
Why are these shortcuts disabled anyway? They do indeed conflict with browser shortcuts, but typically two that you don't care about when you work on a notebook ("show downloads" and "type a ? in the address bar").

**Comment by alexbw** [comment]
+1 for re-enabling these

**Comment by cicocn** [comment]
+ 100 for re-enabling these

**Comment by Carreau** [comment]
Please read the rest of the discussion before posting : 
  - We **will not** re-enable that by default, it breaks some browsers. Commenting +1 or +100 won't help.
  - You can enable that yourself in your configuration. So we don't need to reenable them.
