### ISSUE TITLE
newer nb/nbviewer does not display plot from R kernel (but nb 3.0 does)

### ISSUE THREAD

**Issue by JanSchulz** [jupyter/jupyter_notebook#31]
The following notebooks displays a plot when I open them in a local notebook server (v3.0, chrome, win7), but not in nbviewer: 
* with `[...]`around the uuencoded (png) data: http://nbviewer.ipython.org/gist/JanSchulz/f8ce78434a65717d6783.
* without `[..]` around the uuencoded (png) data: http://nbviewer.ipython.org/gist/randy3k/07d5a3b7db6defae7f87

According to https://github.com/IRkernel/IRkernel/issues/89#issuecomment-94281726 it also does not display in a notebook server v3.1 and v4-dev

Not sure what's the problem here: does the R kernel has to split the lines as the python kernel does it? The display_data spec is kind of silent how to format the data: https://ipython.org/ipython-doc/dev/development/messaging.html#display-data

CC: @randy3k (original bugreport)

**Comment by takluyver** [comment]
I see the plot when I open that file in the live notebook dev version.

I wonder if some of the nbconvert code assumes that `text/plain` is always present? The Python kernel will always offer a plain text repr, and I think we expect that to always exist, though we may not have written that down.

**Comment by takluyver** [comment]
Actually, that can't be it, because you can use e.g. `display_png()` in IPython and that displays without a text/plain format.

**Comment by takluyver** [comment]
I think this is an nbconvert issue. I can reproduce it on master by doing `ipython nbconvert --to html plot_not_visible.ipynb`. There's no error message.

**Comment by takluyver** [comment]
Aha, I think I see it. `application/pdf` is given a higher priority in the HTML output than SVG or PNG for some reason, so it tries to display that, but there's no block in the template to display pdf data. I think reordering the display priority should fix it.

**Comment by takluyver** [comment]
See jupyter/jupyter_nbconvert#5

**Comment by JanSchulz** [comment]
Ok, that means the nbviewer one is dealt with (damn, I was actually writing the issue in that project but switched here before hitting submit). Thanks!

Also thanks for confirming that it is visible in the dev notebook and it's therefore not the formatting of the uuencoded data. Back to step one... :-/

**Comment by JanSchulz** [comment]
Update: it seems that I misunderstood "print preview" and the Jupyter "File -> Print Preview" uses nbconvert in the background -> so it seems that this is both fixed by jupyter/jupyter_nbconvert#5.

Thanks a lot!

**Comment by takluyver** [comment]
Yep, our own 'print preview' menu item uses nbconvert to convert to static HTML.
