### ISSUE TITLE
UI doesn't render if custom.js missing

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_notebook#32]
We load `custom/custom.js` using require along with all of our own modules, and `page.show()` is called in the success callback for that require call. So if there's a 404 on custom.js, you're left with a blank page, and only a message at the JS console says what the problem is.

We should load custom.js separately, since it doesn't matter if it's not there.

It would also be good to have something more informative than a blank page if something fails to load, but that's not the focus of this issue.

**Comment by minrk** [comment]
It shouldn't be possible for custom.js to be missing. This is a bug introduced by #16.

**Comment by minrk** [comment]
Actually, this doesn't appear to be true. I ran master without any custom.js, and it loads fine.

**Comment by takluyver** [comment]
Well, I ran master and it didn't load, but when I commented out the `'custom/custom'` line in main.js, it worked. Maybe it was cached when you tried?

**Comment by minrk** [comment]
I can't seem to make it 404. Did you restart your nbserver? #16 changed the URL for custom from `/static/custom` to `/custom` since it's handled specially. What do you see at `http://localhost:8888/custom/custom.js`?

**Comment by takluyver** [comment]
Ah, I must have pulled while I had a notebook server running. Sorry about that.
