### ISSUE TITLE
Export ipynb directly to Gist (feature idea)

### ISSUE THREAD

**Issue by mdshw5** [jupyter/jupyter_notebook#39]
An export option that interacts with the gist API would be very useful for sharing notebooks. Currently this involves: `Download as > Open in text editor > Copy contents > paste into Gist`. Copy/paste can be replaced by direct file upload to Gist, but really there is no reason to "download" the JSON to upload it to Gist, especially if the notebook server is in the same machine as the browser client.

**Comment by Carreau** [comment]
While this is usefull,  why gist more than something else in the core ? 

You can use extensions like [this one](https://github.com/minrk/ipython_extensions#gist) for that.

**Comment by Carreau** [comment]
More generally you have a bunch of extensions here : https://github.com/ipython-contrib/IPython-notebook-extensions

**Comment by mdshw5** [comment]
I actually had no idea about the extensions, so thanks for pointing me in the right direction!

**Comment by Carreau** [comment]
The all point of IPython in general is to be a base layer, any "extra" should be built on top of it, like storing notebook, on google drive, PostgreSQL.... by digging a bit you can find hundreds of customisation.
