### ISSUE TITLE
Move backbone js to widgets?

### ISSUE THREAD

**Issue by jdfreder** [jupyter/jupyter_notebook#49]
Since nothing in the notebook ATM relies on backbone.js, should we move it to the widgets?  The only reason I could see for us to leave it is if @Carreau want's to use it sometime soon with the notebook model stuff.

**Comment by minrk** [comment]
Based on our conversations about planned notebook refactors, using backbone for non-widget components seems likely in the future, so I probably wouldn't bother removing it. But if you think it's better to move it to widgets, that's fine with me.

**Comment by jdfreder** [comment]
No that's okay, having it here is easier for now.
