### ISSUE TITLE
Specification of kernel directory on command line?

### ISSUE THREAD

**Issue by mikecroucher** [jupyter/jupyter_notebook#53]
Kernel specification files can currently be one of two locations - System wide or user specific.

Would it be possible to add the ability to specify a kernel directory on the command line? Something like

`ipython notebook --kernel_dir=/Users/me/my_kernels/`

This could take precedence over the other 2 locations. 

One example where this would be useful:
I'm currently trying to build a portable Jupyter install on windows that includes an R kernel. It's for teaching use on a heavily locked-down managed desktop.

The install is based on the PortablePython project and works reasonably well. I have 2 problems, however:

- I have to install kernels to the user-profile which defeats the portability somewhat.
- If I move the directory containing the portable install, I have to regenerate my kernels.

The enhancement proposed here would fix everything since I could specify the kernel_dir as a relative path in a launch shortcut.

**Comment by takluyver** [comment]
Is `sys.prefix` within the portable install directory? You should be able to put kernel specs in `sys.prefix + '/share/jupyter/kernels/'` and it will find them.

**Comment by mikecroucher** [comment]
Yes, that works nicely. Thank you!
Furthermore, If I put the portable R folder within the directory specified by sys.prefix, this kernel appears to works fine:

`
{"argv": ["R/R-Portable/App/R-Portable/bin/i386/R.exe","-e","IRkernel::main()",
"--args","{connection_file}"],
 "display_name":"Portable R"
}
`

I'm going to test the portability by moving between machines but things are looking good!
Thank's for the swift and useful reply!

**Comment by takluyver** [comment]
Great. I'll leave this open because I think specifying a relative path in argv works by happy coincidence rather than deliberate design, and we might want to formalise a way to do that.

**Comment by mikecroucher** [comment]
Thanks. For info, here are the steps I took to get everything working using Portable Python and Portable R

http://www.walkingrandomly.com/?p=5734

**Comment by takluyver** [comment]
Great, thanks for writing that up. It looks like portable builds of Python will be an official thing when Python 3.5 comes out, so we won't have to rely on a not-very-maintained third party build. I quite like the idea of making 'Jupyter on a stick' - a USB stick with Jupyter, IPython, R and whatever else makes sense.

**Comment by takluyver** [comment]
jupyter/jupyter_client#8 would make it possible to specify an executable with a relative path from sys.prefix, like `['{prefix}/bin/R', ...]`.
