### ISSUE TITLE
Notebook file list shows files with "hidden" attribute set on Windows

### ISSUE THREAD

**Issue by chrish42** [jupyter/jupyter_notebook#62]
Starting a Jupyter notebook on my home directory on Windows, I see a bunch of files that have the "hidden" attribute set on Windows (like user registry files, etc.). Given that the likelihood of needing to open these hidden files in a notebook is very small, it would be nice if they were also hidden by default, so as not to needlessly pollute the list of files in Windows.

**Comment by takluyver** [comment]
Do you know how to check that attribute from Python? None of the core devs are regular Windows users.

**Comment by minrk** [comment]
To check FILES_ATTRIBUTE_HIDDEN on Windows: `GetFileAttributesW(u'abspath') & 0x02`. See #63
