### ISSUE TITLE
Rpy/rmagic problem:  ReferenceError: marked is not defined "ipython notebook"

### ISSUE THREAD

**Issue by jeffalstott** [jupyter/jupyter_notebook#65]
Had some older notebooks. Updated to the latest IPython, and so am now into Jupyter. Opened up some notebooks and was surprised to see warnings about lack of backward compatibility. Oh well. But when I opened the notebooks with `rmagic` in them, I was even more surprised to see the notebooks could be opened. I got this error: 

`ReferenceError: marked is not defined "ipython notebook"` 

and a blank notebook. Thanks goodness I didn't save the blank notebook, or the data would have been gone! 

Is this a known problem? Now what?

**Comment by minrk** [comment]
IPython 3.1 or master? Can you share any of the older notebooks? What version are you upgrading from? Are you using conda or pip? What platform, Python version, and how did you install IPython?

The r magic was removed from IPython a while ago. It's part of rpy2 now.

**Comment by jeffalstott** [comment]
Linux. Using conda, which brings us to IPython 3.0.0. Just did `conda update` to the latest version of Anaconda. 

When creating a new notebook and using `%load_ext rmagic`, I get this warning:

```
/home/jeffrey_alstott/anaconda3/lib/python3.4/site-packages/IPython/extensions/rmagic.py:693: UserWarning: The rmagic extension in IPython is deprecated in favour of rpy2.ipython. If available, that will be loaded instead.
http://rpy.sourceforge.net/
  warnings.warn("The rmagic extension in IPython is deprecated in favour of "
```

Unfortunately the notebooks themselves contain sensitive data, which of course adds to the consternation of not being able to access them. I may be able to find a similarly non-working notebook without sensitive data and upload it on nbviewer? Or to somewhere else?

**Comment by minrk** [comment]
As the warning message states, the rmagic that ships with IPython is deprecated. That functionality is now part of rpy2, available as `%load_ext rpy2.ipython`.

Upload wherever you are most comfortable. [gists](https://gist.github.com/) are common.  nbviewer doesn't host anything, it's just a renderer of publicly available URLs.

Can you post more of the javascript console output when it fails? Can you open the notebook in an incognito/private browsing window, and see if that works? Do you have anything in custom.js?

**Comment by jeffalstott** [comment]
Good thinking on the custom.js. I do in fact have things there, and they
are throwing errors:


```
:8888/static/notebook/js/celltoolbarpresets/default.js?v=20150503182811:48
Default extension for cell metadata editing loaded.
:8888/static/notebook/js/celltoolbarpresets/rawcell.js?v=20150503182811:82
Raw Cell Format toolbar preset loaded.
:8888/static/notebook/js/celltoolbarpresets/slideshow.js?v=20150503182811:43
Slideshow extension for metadata editing loaded.
:8888/static/base/js/utils.js?v=20150503182811:29 Loaded extension:
usability/python-markdown
:8888/nbextensions/usability/execute_time/ExecuteTime.js?v=20150503182811:21
patching codecell to trigger ExecuteCell.ExecuteTime
:8888/nbextensions/usability/execute_time/ExecuteTime.js?v=20150503182811:178
Execute Timings loaded
:8888/static/base/js/utils.js?v=20150503182811:29 Loaded extension:
usability/execute_time/ExecuteTime
:8888/static/base/js/utils.js?v=20150503182811:37 Failed to load
extension(s): Array[1] TypeError: Cannot read property 'toLowerCase' of
undefined
:8888/static/base/js/utils.js?v=20150503182811:29 Loaded extension:
usability/codefolding/codefolding
http://localhost:8888/static/custom/usability/execute_time/ExecuteTime.css
Failed to load resource: the server responded with a status of 404 (Not
Found)
http://localhost:8888/static/components/codemirror/lib/codemirror?v=20150503182811
Failed to load resource: the server responded with a status of 404 (Not
Found)
require.js:141 Uncaught Error: Script error for:
/static/components/codemirror/lib/codemirror
http://requirejs.org/docs/errors.html#scripterror
http://localhost:8888/static/components/codemirror/addon/fold/foldcode?v=20150503182811
Failed to load resource: the server responded with a status of 404 (Not
Found)
require.js:141 Uncaught Error: Script error for:
/static/components/codemirror/addon/fold/foldcode
http://requirejs.org/docs/errors.html#scripterror
:8888/static/notebook/js/notebook.js?v=20150503182811:2119 Notebook failed
to load from JSON: ReferenceError: marked is not defined
:8888/static/services/sessions/session.js?v=20150503182811:52 Session:
kernel_created (487e0ecc-e3dc-4327-a983-4b179c5056d3)
:8888/static/services/kernels/kernel.js?v=20150503182811:436 Starting
WebSockets:
ws://localhost:8888/api/kernels/6f04d9d4-77af-4a74-b373-7b6ee96d0a40
:8888/static/services/kernels/kernel.js?v=20150503182811:97 Kernel:
kernel_connected (6f04d9d4-77af-4a74-b373-7b6ee96d0a40)
:8888/static/services/kernels/kernel.js?v=20150503182811:97 Kernel:
kernel_ready (6f04d9d4-77af-4a74-b373-7b6ee96d0a40)
http://localhost:8888/static/custom/usability/execute_time/ExecuteTime.css
Failed to load resource: the server responded with a status of 404 (Not
Found)
underscore-min.map:1 GET
http://localhost:8888/static/components/underscore/underscore-min.map 404
(Not Found)
backbone-min.map:1 GET
http://localhost:8888/static/components/backbone/backbone-min.map 404 (Not
Found)
```

I added these ages ago. What is the right way to turn these off with the
current Jupyter setup?

**Comment by jeffalstott** [comment]
And now I've figured it out. In order to remove this problem, I just needed
to deactivate two /static/custom/custom.js extensions I had:

```
IPython.load_extensions('usability/execute_time/ExecuteTime')
IPython.load_extensions('usability/python-markdown')
```

Commenting out both of these lines fixed the problem.
